# Generated by Django 5.2.3 on 2025-12-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
